### ISSUE TITLE
Setting up advice

### ISSUE THREAD

**Issue by mamelmahdy** [mindleaving/gedash#1]
Hey Jan,

Great work on this! We are in need of your help to get this working for our GE Dash 5000 (hoping it will be the same as your 4000 model). We are a startup hoping to use the raw data from the Dash to refine our algorithm for our wearable vitals monitoring device. Currently have the Dash connected to our PC through a network switch. Loaded up your script on Visual Studio, and then changed the IP addresses to match ours. 

Running the the target NetworkCommunication opens a command prompt briefly and then closes (debug shows The program '[964] NetworkCommunication.exe' has exited with code 0 (0x0).). Running the target CentralMonitorGUI opens a blank white screen, and not much else. Is there some other configuration setup we are missing?

Any help would be greatly appreciated!

**Comment by mindleaving** [comment]
Hi mamelmahdy.

Thank you for trying my project.
CentralMonitorGUI is the right startup project. The window is empty because no monitor was detected. As soon as a monitor is detected, it will show up. NetworkCommunication is the library containing the actual code and the only reason why it has a Main-method and can start up is because I used it for debugging before implementation of CentralMonitorGUI. NetworkCommunication is hence not intended for startup.
I'm currently helping another team setting up the GE Dash 5000 and know that it can work. 

There is nothing that needs setup in my program and you hence have to focus on your network setup:
1) Make sure you have IP settings that allow the device and the PC to communicate. If you have a subnet mask of 255.255.255.0 and an IP for the PC of 192.168.0.100, then your monitor could have 192.168.0.101. Make sure there are no other devices on the network with the same IP address.
2) Make sure CentralMonitorGUI is not blocked by a firewall.

Hope that was helpful and that you can get it up and running.

**Comment by mamelmahdy** [comment]
Hey Jan,

Thank you! I was able to get the monitor on the network by figuring out how to change it's IP address to match an open IP on the network. Thanks for your advice! I was able to find a file for the SPO2 data. Can I obtain a file for the other vitals, EKG and respiration rate too? Is it because I don't have the EKG leads on?

**Comment by mamelmahdy** [comment]
Awesome...I just connected myself to the EKG and I was able to get the respiration and EKG files! This is a great thing you have made here. Well done!

**Comment by mindleaving** [comment]
Glad I could help and that you got it working. Good job!
