### ISSUE TITLE
Building the project

### ISSUE THREAD

**Issue by jasonlim97xp** [mindleaving/gedash#9]
Hi, I was able to download the exe file and get the project to work on my Dash 3000 unit. However, we're looking to enhance certain capabilities within the project by editing the code itself. Could I know how could I build the project locally on my computer and then run it on Visual Studio?

We're looking to enhance the capabilities in the NetworkCommunication module.

**Comment by mindleaving** [comment]
Hi @jasonlim97xp 
Thanks for the interest in the project.
Building the project should be as easy as

1. Clone the project and checkout the master-branch
2. Open the solution file "GEDash4000.sln" in Visual Studio
3. Select "NetworkCommunication" as your startup project.
4. Edit the two IP addresses at the top of Program.cs of the NetworkCommunication project
5. Build and run it.

If you want to test that you have a working connection between the monitor and your PC run the "CentralMonitorGUI"-project first. If the network setup is correct, the monitor should be auto-detected. Otherwise you see an empty window.

**Comment by mindleaving** [comment]
Be aware that NetworkCommunication doesn't output any information. You need to add event listeners and logging at your points of interest, e.g. after line 44 you could add an event listener to the DiscoveryMessageReceived-event of discoveryMessageReceiver and log that a monitor has been detected.

**Comment by jasonlim97xp** [comment]
That's great! I'm able to build the project already. 
Thank you very much!
